export const fonts = [
  {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontDisplay: 'swap',
    fontWeight: 400,
    src: `local('Poppins'), local('Poppins'), url(/fonts/Poppins-Regular.ttf) format('opentype')`,
    font: '/fonts/Poppins-Regular.ttf',
    type: 'opentype',
  },
  {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontDisplay: 'swap',
    fontWeight: 500,
    src: `local('Poppins'), local('Poppins'), url(/fonts/Poppins-Medium.ttf) format('opentype')`,
    font: '/fonts/Poppins-Medium.ttf',
    type: 'opentype',
  },
  {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontDisplay: 'swap',
    fontWeight: 600,
    src: `local('Poppins'), local('Poppins'), url(/fonts/Poppins-SemiBold.ttf) format('opentype')`,
    font: '/fonts/Poppins-SemiBold.ttf',
    type: 'opentype',
  },
  {
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontDisplay: 'swap',
    fontWeight: 700,
    src: `local('Poppins'), local('Poppins'), url(/fonts/Poppins-Bold.ttf) format('opentype')`,
    font: '/fonts/Poppins-Bold.ttf',
    type: 'opentype',
  },
  {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontDisplay: 'swap',
    fontWeight: 400,
    src: `local('Inter'), local('Inter'), url(/fonts/Inter-Regular.ttf) format('opentype')`,
    font: '/fonts/Inter-Regular.ttf',
    type: 'opentype',
  },
  {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontDisplay: 'swap',
    fontWeight: 500,
    src: `local('Inter'), local('Inter'), url(/fonts/Inter-Medium.ttf) format('opentype')`,
    font: '/fonts/Inter-Medium.ttf',
    type: 'opentype',
  },
  {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontDisplay: 'swap',
    fontWeight: 600,
    src: `local('Inter'), local('Inter'), url(/fonts/Inter-SemiBold.ttf) format('opentype')`,
    font: '/fonts/Inter-SemiBold.ttf',
    type: 'opentype',
  },
  {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontDisplay: 'swap',
    fontWeight: 700,
    src: `local('Inter'), local('Inter'), url(/fonts/Inter-Bold.ttf) format('opentype')`,
    font: '/fonts/Inter-Bold.ttf',
    type: 'opentype',
  },
  {
    fontFamily: 'source_serif',
    fontStyle: 'normal',
    fontDisplay: 'swap',
    fontWeight: 400,
    src: `local('source_serif'), local('source_serif'), url(/fonts/sourceserifpro-regular-webfont.ttf) format('opentype')`,
    font: '/fonts/sourceserifpro-regular-webfont.ttf',
    type: 'opentype',
  },
  {
    fontFamily: 'source_serif',
    fontStyle: 'normal',
    fontDisplay: 'swap',
    fontWeight: 700,
    src: `local('source_serif'), local('source_serif'), url(/fonts/sourceserifpro-bold-webfont.ttf) format('opentype')`,
    font: '/fonts/sourceserifpro-bold-webfont.ttf',
    type: 'opentype',
  },
] as const;
